wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("create/", views.create, name="create"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import markdown2
import random

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from . import util


class CreateNewEntry(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Entry title'}))
    content = forms.CharField(label="", widget=forms.Textarea(
        attrs={'class': 'form-control my-3', 'placeholder': "Entry content ..."}))
    edit = forms.BooleanField(
        initial=False, widget=forms.HiddenInput(), required=False)


def index(request):
    query = request.GET.get('q', '')
    if not query:
        return render(request, "encyclopedia/index.html", {
            "search": False,
            "entries": util.list_entries(),
        })
    elif util.get_entry(query) is not None:
        return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': query}))
    else:
        entries_list = []
        for entry in util.list_entries():
            if query.lower() in entry.lower():
                entries_list.append(entry)
        return render(request, "encyclopedia/index.html", {
            "search": True,
            "title": query,
            "entries": entries_list,
        })


def wiki(request, title):
    if title == "random":
        random_entry = random.choice([i for i in util.list_entries()])
        entry = util.get_entry(random_entry)
        return render(request, "encyclopedia/wiki.html", {
            "has_entry": True,
            "title": random_entry,
            "content": markdown2.Markdown().convert(entry),
        })
    entry = util.get_entry(title)
    if entry is None:
        return render(request, "encyclopedia/wiki.html", {
            "has_entry": False,
            "content": "No such entry available.",
        })
    else:
        return render(request, "encyclopedia/wiki.html", {
            "has_entry": True,
            "title": title,
            "content": markdown2.Markdown().convert(entry),
        })


def create(request):
    if request.method == "POST":
        form = CreateNewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title) is None or form.cleaned_data["edit"] is True:
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:wiki", kwargs={'title': title}))
            else:
                return render(request, "encyclopedia/create.html", {
                    "form": form,
                    "exist": True,
                    "title": title
                })
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form,
                "exist": False
            })
    else:
        return render(request, "encyclopedia/create.html", {
            "form": CreateNewEntry(),
            "existing": False
        })


def edit(request, title):
    form = CreateNewEntry()
    form.fields["title"].initial = title
    form.fields["title"].widget = forms.HiddenInput()
    form.fields["content"].initial = util.get_entry(title)
    form.fields["edit"].initial = True
    return render(request, "encyclopedia/create.html", {
        "form": form,
        "edit": form.fields["edit"].initial,
        "title": form.fields["title"].initial
    })

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create new entry
{% endblock %}

{% block body %}

{% if edit %}
<h1>Editing {{ title }}</h1>
{% else %}
<h1>Create new entry</h1>
{% endif %}


{% if exist %}
<div class="alert" role="alert">
    <a href="{% url 'encyclopedia:wiki' title %}" class="alert-link">{{ title }}</a> entry already exists.
</div>
{% endif %}

<form action="{% url 'encyclopedia:create' %}" method="post" class="form my-4">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-outline-secondary">Create</button>
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}


{% if search %}
<h2>Result for <b>{{ title }}</b></h2>
{% else %}
<h1>All Pages</h1>
{% endif %}

<ul>
    {% for entry in entries %}
    <li><a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %} | Wiki</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="GET">
                    {% csrf_token %}
                    <input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:wiki' 'random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>

</body>

</html>

wiki/encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}

{% if has_entry %}
<div class="container">
    {{ content|safe }}
    <hr class="hr-only">
    <a href="/wiki/{{ title }}/edit" class="btn btn-outline-secondary">Edit</a>
</div>
{% else %}
<h1>{{ content|safe }}</h1>
{% endif %}

{% endblock %}